# We want to use the KVM-based system, so require sudo
sudo: required
services:
  - docker

before_install:
  - git clone --depth=1 https://github.com/discourse/discourse-plugin-ci
  - git clone --depth=1 https://github.com/discourse/discourse-assign $HOME/plugins/discourse-assign

install: true # Prevent travis doing bundle install

script:
  - export DOCKER_OPTIONS="-v ${HOME}/plugins/discourse-assign:/var/www/discourse/plugins/discourse-assign"
  - discourse-plugin-ci/script.sh
