plugins:
  code_review_enabled: false
  code_review_github_token: ""
  code_review_sync_to_github: false
  code_review_catch_up_commits: 10
  code_review_allow_private_clone: false
  code_review_pending_tag:
    client: true
    default: "pending"
  code_review_approved_tag:
    client: true
    default: "approved"
  code_review_followup_tag:
    client: true
    default: "follow-up"
  code_review_unmerged_tag: "unmerged"
  code_review_commit_tag: "commit"
  code_review_pull_request_tag: "pull-request"
  code_review_github_webhook_secret: ""
  code_review_allow_self_approval:
    client: true
    default: false
  code_review_auto_assign_on_followup: true
  code_review_auto_unassign_on_approve: true
  code_review_github_organizations: ""
